# Navigation Links
#   To link a homepage widget, specify the URL as a hash `#` followed by the filename of the
#     desired widget in your `content/home/` folder.
#   The weight parameter defines the order that the links will appear in.

[[main]]
  name = "About"
  url = "about"
  weight = 10
  identifier = "about"
  
[[main]]
  name = "Introduction"
  url = "about#introduction"
  weight = 10
  parent = "about"
  
[[main]]
  name = "Objectives"
  url = "about#objectives"
  weight = 20
  parent = "about"

[[main]]
  name = "People"
  url = "people"
  weight = 40
  parent = "about"

[[main]]
  name = "Data"
  weight = 20
  identifier = "data"
  
[[main]]
  name = "Data Contributors"
  url = "partner-curation"
  weight = 10
  parent = "data"

[[main]]
  name = "Datasets"
  url = "data-curation"
  weight = 20
  parent = "data"

[[main]]
  name = "Data Reports"
  url = "data-reports"
  weight = 30
  parent = "data"


[[main]]
  name = "Resources"
  url = "resources"
  weight = 30

[[main]]
  name = "Contact"
  url = "about#contact"
  weight = 40
  
[[main]]
name = "Covid-19"
url = "covid-19"
weight = 50

[[main]]
  pre = "<i class=\"fab fa-github fa-lg\"></i>"
  name = "&nbsp;"
  url = "https://github.com/justicehub-in/justice-hub-docs"
  weight = 60

#[[main]]
#  pre = "<i class=\"fab fa-osi fa-lg\"></i>"
#  name = "&nbsp;"
#  url = "https://taiga.civicdatalab.in/project/apoorv-justice-data-hub/wiki/home"
#  weight = 80

[[main]]
  pre = "<i class=\"fab fa-twitter fa-lg\"></i>"
  name = ""
  url = "https://twitter.com/JusticeHubIndia"
  weight = 70
  
# Link to a PDF of your resume/CV from the menu.
# To enable, copy your resume/CV to `static/files/cv.pdf` and uncomment the lines below.
# [[main]]
#    name = "CV"
#    url = "files/cv.pdf"
#    weight = 70
