---
title: "Data Reports"
draft: no
date: '2020-02-27T00:00:00Z'
linktitle: Justice Hub | Data Reports
summary: Data curation status for the Justice Hub
  legal datasets to be released in the first phase of the project
lastmod: '2020-02-27T00:00:00Z'
type: post
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r preparing data, message=FALSE, warning=FALSE, include=FALSE}
library(googlesheets4)
library(dplyr)
library(knitr)
library(kableExtra)
library(glue)
library(stringr)
# Read google form to access data reports
form_responses_link <- 'https://docs.google.com/spreadsheets/d/1OX1YcFadTx3IpUqae-7yhuZqt-ebAz9skD9hEab10ME/edit?usp=sharing'

# This is a public sheet, hence OAuth is not required
sheets_deauth()

# Read all form responses
form_responses <- sheets_read(ss = form_responses_link)

form_responses$org_alias <-
  form_responses$`Organisation Name` %>% unique() %>% stringr::str_to_lower() %>% stringr::str_trim()
form_responses$org_alias[form_responses$org_alias == 'veratech'] <- 'veratechIN'

# org_alias <- 'nipfp'

# Creating a data report dataframe

cols_to_consider <- c("Organisation Name", "org_alias","Timestamp", "Title", "Dataset URL", "Dataset issue report", "Data Issue Status")
master_report_df <- form_responses[,cols_to_consider]
master_report_df$Timestamp <- as.Date(master_report_df$Timestamp)
names(master_report_df)[which(names(master_report_df) == 'Timestamp')] <- 'Date added'
```

```{r table output, echo=FALSE, message=FALSE, warning=FALSE}

master_report_df$title_with_link <-
  ifelse(
    !is.na(master_report_df$Title),
    master_report_df$Title %>%  str_replace_all(pattern = '[\\(\\)\\-]',replacement = ' ') %>% str_trim() %>% str_replace_all(pattern = '[:space:]+', replacement = '-') %>% str_trim(side = 'both'),
    master_report_df$Title
  )

master_report_df$`Organisation Name` <- text_spec(master_report_df$`Organisation Name`, link = glue('../data-curation/{master_report_df$org_alias}'))

master_report_df$title_with_link <- glue('../data-curation/{master_report_df$org_alias}/{master_report_df$title_with_link}') %>% str_to_lower()
  
master_report_df$Title <- text_spec(x = master_report_df$Title, link = master_report_df$title_with_link)

master_report_df$org_alias <- NULL
master_report_df$title_with_link <- NULL

report_table <- master_report_df %>% knitr::kable(escape = FALSE)
report_table
```

